kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: eventbus
spec:
  path: /
  to:
    kind: Service
    name: eventbus
    weight: 100
  port:
    targetPort: 4005-tcp
  wildcardPolicy: None